### ISSUE TITLE
Non-Registered User - Wine Search

### ISSUE THREAD

**Issue by Diana20920** [WeatherVine/front_end#13]
- [ ] must clarify question in #8 

As a non-registered user
After I click on the link/button to search wine types
I am taken to the wine search page that has drop-down options for 
type of wine 
region
vintage of wine
And a button to submit my search 
Which will take the non-registered user to the results page.

- [ ] There are also buttons to the register/login page. (may be remove this since it will be in the navbar for all pages)

**Comment by aschwartz1** [comment]
Duplicate of #11 , closing & consolidating there.
