### ISSUE TITLE
 FE Gems

### ISSUE THREAD

**Issue by Wil-McC** [WeatherVine/front_end#19]
- [x] Faker
- [x] Figaro
- [x] SimpleCov
- [x] FactoryBot
- [x] Shoulda-Matchers
- [x] Capybara
- [x] Webmock
- [x] VCR
- [x] RuboCop
- [x] launchy
- [x] orderly

**Comment by Diana20920** [comment]
I confirmed that these gems have been added to the `Gemfile` and assigned @klatour324 and @Trevorsuter so I can close this issue. Please add/remove people that may or may not have worked on this section as you see fit 😃
