### ISSUE TITLE
Add Config Variables to Heroku

### ISSUE THREAD

**Issue by Diana20920** [WeatherVine/front_end#26]
At the moment, Travis is deploying to Heroku. 
However, because there are no variables setup on Heroku, we get an `invalid request` when attempting to sign in.

- [ ] User can sign in while on Heroku with their Google account

**Comment by aschwartz1** [comment]
Added the back end URL to heroku's config.

Can't test it as of now b/c current build's OAuth isn't working correctly (it redirects to Google sign in, which displays an error).
